import { StyleSheet } from "react-native";
import { colors, typography, spacing } from "../../styles/tokens";

export const homeStyles = StyleSheet.create({
  greeting: { ...typography.steps, color: colors.brownDark, marginBottom: spacing.xs },
  greetingName: { color: colors.greenDark },
  loadingContainer: { flex: 1, justifyContent: "center", alignItems: "center", padding: spacing.x2l },
  companyStatsTitle: { fontSize: 16, fontWeight: "700", color: colors.brownDark, marginBottom: spacing.x3s },
  companyStatsRow: { flexDirection: "row", justifyContent: "space-around" },
  companyStatItem: { alignItems: "center" },
  companyStatValue: { fontSize: 28, fontWeight: "800", color: colors.greenDark },
  companyStatLabel: { fontSize: 12, color: colors.olive, marginTop: 4 },
  card: { borderWidth: 1, borderColor: colors.creamDark, borderRadius: 12 },
  cardLight: { backgroundColor: colors.creamLight },
  cardBody: { gap: spacing.x2s, padding: spacing.xs },
  stepsHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  labelSmall: { fontSize: 13, color: colors.olive },
  stepsValue: { fontSize: 24, fontWeight: "800", color: colors.brownDark },
  stepsGoal: { fontSize: 18, fontWeight: "600", color: colors.olive },
  progressBarBg: { height: 8, borderRadius: 9999, backgroundColor: colors.creamDark, overflow: "hidden" },
  progressBarFill: { height: "100%", borderRadius: 9999, backgroundColor: colors.greenDark },
  progressBarFillGreen: { height: "100%", borderRadius: 9999, backgroundColor: colors.greenBright },
  stepsFooter: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  streakRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  streakLeft: { flexDirection: "row", alignItems: "center", gap: spacing.x2s },
  streakIconBox: { width: 48, height: 48, borderRadius: 8, backgroundColor: "rgba(139, 69, 19, 0.1)", alignItems: "center", justifyContent: "center" },
  streakDays: { fontSize: 24, fontWeight: "800", color: colors.error },
  streakLabel: { fontSize: 14, color: colors.olive, marginTop: 4 },
  streakBadge: { backgroundColor: colors.creamDark, borderRadius: 9999, paddingHorizontal: spacing.xs, paddingVertical: spacing.x3s },
  streakBadgeText: { fontSize: 14, fontWeight: "700", color: colors.greenDark },
  quickActions: { flexDirection: "row", flexWrap: "wrap", gap: spacing.x2s, marginBottom: spacing.xs },
  actionTile: { width: "48%", borderWidth: 1, borderColor: colors.creamDark, borderRadius: 12, backgroundColor: colors.creamLight, padding: spacing.xs, alignItems: "center", gap: spacing.x3s },
  actionLabel: { fontSize: 15, fontWeight: "600", color: colors.brownDark, textAlign: "center" },
  sectionTitle: { fontSize: 18, fontWeight: "700", color: colors.brownDark, marginBottom: spacing.x2s },
  declCard: { borderWidth: 1, borderColor: colors.creamDark, borderRadius: 12, overflow: "hidden", width: 188 },
  declCardBody: { padding: spacing.xs, gap: spacing.x2s },
  declCardInfo: { gap: spacing.x4s },
  declCardLabel: { fontSize: 14, fontWeight: "600", color: colors.brownDark },
  declCardPointsRow: { flexDirection: "row", alignItems: "baseline", gap: spacing.x4s },
  declCardPoints: { fontSize: 24, fontWeight: "800", color: colors.greenDark },
  declCardPointsLabel: { fontSize: 14, fontWeight: "600", color: colors.olive },
  challengeOrg: { fontSize: 12, fontWeight: "700", color: colors.greenDark, letterSpacing: 1 },
  challengeTitle: { fontSize: 18, fontWeight: "700", color: colors.brownDark },
  challengeCard: { backgroundColor: colors.creamMedium, borderColor: colors.creamDark, borderWidth: 1, borderRadius: 12, padding: spacing.xs, marginTop: 10 },
});
