export const ACTIVITY_CONFIG = {
  CATEGORY_DAILY_CAP: 50,
  GLOBAL_DAILY_CAP: 120,
  SYNERGY_BONUS_PCT: 0.2,
  DIMINISHING_TIERS: [1.0, 0.5, 0.25, 0.0],
  DECLARATIONS_DAILY_LIMIT: 3,
  EXP_PER_DECLARATION: 25,
  LEADERBOARD_PTS_PER_DECLARATION: 10,
  LEGACY_ACTIVITY_EXP: 10,
  LEGACY_ACTIVITY_LB_PTS: 5,
} as const;
