import { StyleSheet } from "react-native";
import { colors, radius, spacing } from "../../styles/tokens";

export const ekoStyles = StyleSheet.create({
  card: { borderWidth: 1, borderColor: colors.creamDark, borderRadius: radius.md },
  cardLight: { backgroundColor: colors.creamLight },
  cardBody: { gap: spacing.x2s, padding: spacing.xs },
  row: { flexDirection: "row", alignItems: "center", gap: spacing.xs },
  stageImage: { width: 48, height: 48 },
  stageInfo: { flex: 1 },
  stageName: { fontSize: 20, fontWeight: "700", color: colors.brownDark },
  expLabel: { fontSize: 14, color: colors.olive, marginTop: 4 },
  progressBarBg: { height: 8, borderRadius: radius.full, backgroundColor: colors.creamDark, overflow: "hidden" },
  progressBarFill: { height: "100%", borderRadius: radius.full, backgroundColor: colors.greenDark },
  nextStageText: { fontSize: 12, color: colors.olive },
  btnPrimary: { backgroundColor: colors.primary, borderRadius: radius.md, paddingVertical: spacing.x2s, paddingHorizontal: spacing.md, alignItems: "center", justifyContent: "center" },
  btnPrimaryText: { fontSize: 15, fontWeight: "600", color: colors.primaryForeground },
  errorBanner: { padding: spacing.x2s, borderRadius: radius.sm, marginBottom: spacing.x2s, backgroundColor: "rgba(139, 69, 19, 0.1)" },
  errorBannerText: { fontSize: 14, fontWeight: "700", color: colors.error },
  resultBanner: { padding: spacing.x2s, borderRadius: radius.sm, marginBottom: spacing.x2s, gap: spacing.x3s, backgroundColor: colors.creamDark },
  resultText: { fontSize: 14, fontWeight: "700", color: colors.brownDark },
  badgesRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing.x3s },
  badge: { paddingHorizontal: spacing.x3s, paddingVertical: spacing.x4s, borderRadius: 6 },
  badgeText: { fontSize: 12, fontWeight: "600", color: colors.brownDark },
  remainingText: { fontSize: 12, color: colors.olive, marginTop: 4 },
  categoryBlock: { marginBottom: spacing.x2s, borderRadius: radius.sm, overflow: "hidden", borderWidth: 1, borderColor: colors.creamDark },
  categoryHeader: { paddingHorizontal: spacing.xs, paddingVertical: spacing.x3s },
  categoryHeaderText: { fontSize: 14, fontWeight: "700" },
  activityRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: spacing.x2s, paddingHorizontal: spacing.xs, borderTopWidth: 1, borderTopColor: colors.creamDark },
  activityRowDone: { opacity: 0.55 },
  activityLeft: { flexDirection: "row", alignItems: "center", gap: spacing.x2s, flex: 1 },
  activityInfo: { flex: 1 },
  activityName: { fontSize: 14, fontWeight: "600", color: colors.brownDark },
  activityMeta: { fontSize: 12, color: colors.olive, marginTop: 4 },
  textMuted: { opacity: 0.6 },
  badgeOneTime: { fontSize: 11, fontWeight: "600", color: colors.greenBright, backgroundColor: colors.greenLight, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4, overflow: "hidden" },
  doneCircle: { width: 32, height: 32, borderRadius: radius.full, backgroundColor: colors.olive, alignItems: "center", justifyContent: "center" },
  doneCheck: { color: colors.white, fontSize: 14, fontWeight: "700" },
  addBtn: { backgroundColor: colors.primary, borderRadius: radius.md, width: 36, height: 36, alignItems: "center", justifyContent: "center" },
  addBtnText: { fontSize: 18, fontWeight: "700", color: colors.primaryForeground },
});
