import { StyleSheet } from "react-native";
import { colors, radius } from "../../styles/tokens";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.inputBg },
  fallbackRoot: { flex: 1, justifyContent: "center", alignItems: "center", padding: 40 },
  fallbackTitle: { fontSize: 22, fontWeight: "700", color: colors.deepForest, textAlign: "center" },
  fallbackText: { fontSize: 15, color: colors.slate500, textAlign: "center", marginTop: 8 },
  topbar: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: 32, paddingVertical: 14, backgroundColor: colors.white, borderBottomWidth: 1, borderBottomColor: colors.slate200 },
  topbarRight: { flexDirection: "row", alignItems: "center", gap: 12 },
  navTabs: { flexDirection: "row", backgroundColor: colors.white, borderBottomWidth: 1, borderBottomColor: colors.slate200, paddingHorizontal: 32 },
  navTab: { paddingVertical: 12, paddingHorizontal: 20, borderBottomWidth: 2, borderBottomColor: "transparent" },
  navTabActive: { borderBottomColor: colors.mossGreen },
  navTabText: { fontSize: 14, fontWeight: "600", color: colors.slate500 },
  navTabTextActive: { color: colors.mossGreen },
  body: { paddingHorizontal: 32, paddingTop: 28, paddingBottom: 48 },
  bodyInner: { maxWidth: 1100, width: "100%", alignSelf: "center" },
  pageTitle: { fontSize: 28, fontWeight: "700", color: colors.slate900, marginBottom: 20 },
  sectionTitle: { fontSize: 18, fontWeight: "700", color: colors.slate900, marginBottom: 14, marginTop: 8 },
  errorCard: { backgroundColor: colors.errorBg, borderWidth: 1, borderColor: colors.errorBorder, borderRadius: radius.md, padding: 20, gap: 8 },
  errorText: { fontSize: 16, fontWeight: "600", color: colors.error },
  errorDetail: { fontSize: 14, color: colors.deepForest },
  hintText: { fontSize: 14, color: colors.slate500, marginBottom: 16 },
  statsRow: { flexDirection: "row", gap: 16, marginBottom: 16 },
  statCard: { flex: 1, backgroundColor: colors.white, borderRadius: radius.md, borderWidth: 1, borderColor: colors.slate200, padding: 20, gap: 4 },
  statValue: { fontSize: 32, fontWeight: "800", color: colors.deepForest },
  statLabel: { fontSize: 14, color: colors.slate500, fontWeight: "500" },
  companyMinList: { gap: 4, marginBottom: 16 },
  companyMinRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, paddingVertical: 10, paddingHorizontal: 12 },
  companyMinName: { fontSize: 15, fontWeight: "600", color: colors.slate900 },
  companyMinCount: { fontSize: 13, color: colors.slate500 },
  chartRow: { flexDirection: "row", gap: 8, marginBottom: 24, alignItems: "flex-end" },
  chartCol: { flex: 1, alignItems: "center", gap: 4 },
  chartBarValue: { fontSize: 11, color: colors.slate500, fontWeight: "600" },
  chartBar: { width: "100%", maxWidth: 40, backgroundColor: colors.mossGreen, borderRadius: radius.sm, minHeight: 4 },
  chartLabel: { fontSize: 11, color: colors.slate500, textTransform: "capitalize" },
  activityList: { gap: 8 },
  activityRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.md, padding: 14 },
  activityLeft: { gap: 2 },
  activityName: { fontSize: 15, fontWeight: "600", color: colors.slate900 },
  activityType: { fontSize: 13, color: colors.slate500, textTransform: "capitalize" },
  activityPoints: { fontSize: 16, fontWeight: "700", color: colors.mossGreen },
  tableHeader: { flexDirection: "row", backgroundColor: colors.slate100, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, paddingVertical: 10, paddingHorizontal: 12, marginBottom: 4 },
  tableHeaderCell: { fontSize: 12, fontWeight: "700", color: colors.slate500, textTransform: "uppercase" },
  tableRow: { flexDirection: "row", alignItems: "center", backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, paddingVertical: 12, paddingHorizontal: 12, marginBottom: 4, gap: 4 },
  tableCell: { fontSize: 14, color: colors.slate900 },
  actionBtn: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: radius.sm, borderWidth: 1, alignItems: "center" },
  actionBtnWarn: { borderColor: colors.errorBorder, backgroundColor: colors.errorBg },
  actionBtnSuccess: { borderColor: colors.successBorder, backgroundColor: colors.successBg },
  actionBtnText: { fontSize: 12, fontWeight: "600" },
  inputSmall: { borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, padding: 6, fontSize: 12, color: colors.slate900, backgroundColor: colors.inputBg },
  createCard: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.md, padding: 20, gap: 12, marginBottom: 8 },
  createTitle: { fontSize: 16, fontWeight: "700", color: colors.slate900 },
  createRow: { flexDirection: "row", gap: 8, alignItems: "center" },
  input: { borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, padding: 10, fontSize: 14, color: colors.slate900, backgroundColor: colors.inputBg },
  createBtn: { backgroundColor: colors.mossGreen, borderRadius: radius.sm, paddingVertical: 10, paddingHorizontal: 20 },
  createBtnText: { color: colors.white, fontSize: 14, fontWeight: "700" },
  companyCard: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.md, overflow: "hidden" },
  companyCardHeader: { flexDirection: "row", alignItems: "center", padding: 16 },
  companyName: { fontSize: 16, fontWeight: "700", color: colors.slate900 },
  companyMeta: { fontSize: 13, color: colors.slate500, marginTop: 2 },
  expandIcon: { fontSize: 14, color: colors.slate500, marginLeft: 12 },
  companyDetails: { borderTopWidth: 1, borderTopColor: colors.slate200, padding: 16, gap: 12 },
  tokenActions: { flexDirection: "row", justifyContent: "flex-end" },
  genTokenBtn: { backgroundColor: colors.roleCompany, borderRadius: radius.sm, paddingVertical: 8, paddingHorizontal: 16 },
  genTokenBtnText: { color: colors.white, fontSize: 13, fontWeight: "600" },
  genBigBtn: { backgroundColor: colors.roleCompany, borderRadius: radius.md, paddingVertical: 14, paddingHorizontal: 24, alignItems: "center", marginBottom: 20, alignSelf: "flex-start" },
  genBigBtnText: { color: colors.white, fontSize: 15, fontWeight: "700" },
  tokensTitle: { fontSize: 14, fontWeight: "700", color: colors.slate700 },
  tokenList: { gap: 4 },
  tokenHeader: { flexDirection: "row", backgroundColor: colors.slate100, borderRadius: radius.sm, paddingVertical: 6, paddingHorizontal: 8 },
  tokenHeaderCell: { fontSize: 11, fontWeight: "700", color: colors.slate500, textTransform: "uppercase" },
  tokenRow: { flexDirection: "row", alignItems: "center", paddingVertical: 6, paddingHorizontal: 8, borderBottomWidth: 1, borderBottomColor: colors.slate100 },
  tokenCell: { fontSize: 13, color: colors.slate900 },
  tokenListFull: { gap: 4 },
  tokenTableHeader: { flexDirection: "row", backgroundColor: colors.slate100, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, paddingVertical: 10, paddingHorizontal: 12, marginBottom: 4 },
  tokenTableRow: { flexDirection: "row", alignItems: "center", backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, paddingVertical: 12, paddingHorizontal: 12, marginBottom: 4 },
  roleTab: { paddingVertical: 10, borderRadius: radius.sm, alignItems: "center", backgroundColor: colors.slate100 },
  roleTabActive: { backgroundColor: colors.white, shadowColor: "#000", shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.08, shadowRadius: 3, elevation: 2 },
  roleTabText: { fontSize: 14, fontWeight: "600", color: colors.slate500 },
  roleTabTextActive: { color: colors.slate900 },
  filterRow: { flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 16 },
  filterLabel: { fontSize: 14, fontWeight: "600", color: colors.slate700 },
  filterButtons: { flexDirection: "row", gap: 8, flexWrap: "wrap" },
  filterBtn: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: colors.slate200, backgroundColor: colors.white },
  filterBtnActive: { backgroundColor: colors.mossGreen, borderColor: colors.mossGreen },
  filterBtnText: { fontSize: 13, fontWeight: "600", color: colors.slate600 },
  filterBtnTextActive: { color: colors.white },
  primaryBtn: { backgroundColor: colors.mossGreen, borderRadius: 8, paddingVertical: 12, alignItems: "center", marginBottom: 16 },
  primaryBtnText: { color: colors.white, fontSize: 14, fontWeight: "700" },
  formCard: { backgroundColor: colors.white, borderRadius: 12, padding: 16, marginBottom: 16, borderWidth: 1, borderColor: colors.slate200 },
  formLabel: { fontSize: 13, fontWeight: "600", color: colors.slate700, marginBottom: 4, marginTop: 8 },
  emptyText: { fontSize: 14, color: colors.slate500, textAlign: "center", padding: 20 },
  dangerBtn: { backgroundColor: colors.errorBg, borderRadius: 6, paddingHorizontal: 12, paddingVertical: 6 },
  dangerBtnText: { color: colors.error, fontSize: 12, fontWeight: "600" },
  listRow: { flexDirection: "row", alignItems: "center", padding: 12, backgroundColor: colors.white, borderRadius: 8, marginBottom: 8, borderWidth: 1, borderColor: colors.slate200 },
  listName: { fontSize: 14, fontWeight: "600", color: colors.slate900 },
  listEmail: { fontSize: 12, color: colors.slate500, marginTop: 2 },
  badge: { alignSelf: "flex-start", paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  badgeText: { fontSize: 12, fontWeight: "600" },
  analyticsSelector: { marginBottom: 24 },
  analyticsSelectorLabel: { fontSize: 15, fontWeight: "600", color: colors.slate700, marginBottom: 12 },
  analyticsUserList: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  analyticsUserBtn: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.slate200, backgroundColor: colors.white },
  analyticsUserBtnActive: { backgroundColor: colors.mossGreen, borderColor: colors.mossGreen },
  analyticsUserBtnText: { fontSize: 14, fontWeight: "600", color: colors.slate700 },
  analyticsUserBtnTextActive: { color: colors.white },
  analyticsUserBtnEmail: { fontSize: 11, color: colors.slate500, marginTop: 2 },
  analyticsUserBtnEmailActive: { color: colors.creamLight },
  analyticsUserInfo: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.md, padding: 20, marginBottom: 24, flexDirection: "row", alignItems: "center", gap: 16 },
  analyticsUserName: { fontSize: 20, fontWeight: "700", color: colors.slate900 },
  analyticsUserStage: { fontSize: 14, color: colors.mossGreen, fontWeight: "600" },
  analyticsUserExp: { fontSize: 14, color: colors.slate500, marginLeft: "auto" },
  analyticsPlaceholder: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.md, padding: 48, alignItems: "center" },
  analyticsPlaceholderText: { fontSize: 15, color: colors.slate500 },
  analyticsChartCard: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.md, padding: 24, marginBottom: 20 },
  analyticsChartHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 20 },
  analyticsChartTitle: { fontSize: 18, fontWeight: "700", color: colors.slate900 },
  analyticsChartStats: { flexDirection: "row", gap: 24 },
  analyticsChartStat: { alignItems: "flex-end" },
  analyticsChartStatValue: { fontSize: 20, fontWeight: "700", color: colors.mossGreen },
  analyticsChartStatLabel: { fontSize: 12, color: colors.slate500, fontWeight: "500" },
  analyticsChartRow: { flexDirection: "row", gap: 6, alignItems: "flex-end", minHeight: 180 },
  analyticsChartCol: { flex: 1, alignItems: "center", gap: 4 },
  analyticsChartBarValue: { fontSize: 10, color: colors.slate500, fontWeight: "600" },
  analyticsChartBar: { width: "100%", maxWidth: 48, backgroundColor: colors.mossGreen, borderRadius: radius.sm, minHeight: 4 },
  analyticsChartLabel: { fontSize: 10, color: colors.slate500, textTransform: "capitalize" },
  analyticsLayout: { flexDirection: "row", gap: 24, minHeight: 600 },
  analyticsSidebar: { width: 220, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.md, padding: 16, alignSelf: "flex-start" },
  analyticsSidebarItem: { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 10, paddingHorizontal: 12, borderRadius: radius.sm, marginBottom: 4 },
  analyticsSidebarItemActive: { backgroundColor: colors.slate100 },
  analyticsSidebarIcon: { width: 18, height: 18, alignItems: "center", justifyContent: "center" },
  analyticsSidebarLabel: { fontSize: 14, fontWeight: "500", color: colors.slate600 },
  analyticsSidebarLabelActive: { color: colors.mossGreen, fontWeight: "700" },
  analyticsMain: { flex: 1 },
  periodSelector: { flexDirection: "row", gap: 8, marginBottom: 16 },
  periodBtn: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: colors.slate200, backgroundColor: colors.white },
  periodBtnActive: { backgroundColor: colors.mossGreen, borderColor: colors.mossGreen },
  periodBtnText: { fontSize: 13, fontWeight: "600", color: colors.slate600 },
  periodBtnTextActive: { color: colors.white },
  customDateRow: { flexDirection: "row", gap: 12, marginBottom: 16 },
  customDateField: { flex: 1 },
  customDateLabel: { fontSize: 13, fontWeight: "600", color: colors.slate700, marginBottom: 4 },
  customDateInput: { borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, padding: 10, fontSize: 14, color: colors.slate900, backgroundColor: colors.white },
});
