import { StyleSheet } from "react-native";
import { colors, typography, radius, spacing } from "../../styles/tokens";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.inputBg },
  fallbackRoot: { flex: 1, justifyContent: "center", alignItems: "center", padding: spacing.xl },
  fallbackTitle: { fontSize: 22, fontWeight: "700", color: colors.deepForest, textAlign: "center" },
  fallbackText: { fontSize: 15, color: colors.slate500, textAlign: "center", marginTop: spacing.x3s },
  topbar: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: spacing.lg, paddingVertical: 14, backgroundColor: colors.white, borderBottomWidth: 1, borderBottomColor: colors.slate200 },
  topbarRight: { flexDirection: "row", alignItems: "center", gap: spacing.x2s },
  navTabs: { flexDirection: "row", backgroundColor: colors.white, borderBottomWidth: 1, borderBottomColor: colors.slate200, paddingHorizontal: spacing.lg },
  navTab: { paddingVertical: spacing.x2s, paddingHorizontal: spacing.sm, borderBottomWidth: 2, borderBottomColor: "transparent" },
  navTabActive: { borderBottomColor: colors.mossGreen },
  navTabText: { fontSize: 14, fontWeight: "600", color: colors.slate500 },
  navTabTextActive: { color: colors.mossGreen },
  body: { paddingHorizontal: spacing.lg, paddingTop: 28, paddingBottom: spacing.x2l },
  bodyInner: { maxWidth: 1100, width: "100%", alignSelf: "center" },
  pageTitle: { ...typography.h1, color: colors.slate900, marginBottom: spacing.sm },
  sectionTitle: { fontSize: 18, fontWeight: "700", color: colors.slate900, marginBottom: 14, marginTop: spacing.x3s },
  errorCard: { backgroundColor: colors.errorBg, borderWidth: 1, borderColor: colors.errorBorder, borderRadius: radius.md, padding: spacing.sm, gap: spacing.x3s },
  errorText: { ...typography.h3, color: colors.error },
  errorDetail: { fontSize: 14, color: colors.deepForest },
  hintText: { fontSize: 14, color: colors.slate500, marginBottom: spacing.xs },
  statsRow: { flexDirection: "row", gap: spacing.xs, marginBottom: spacing.xs },
  statCard: { flex: 1, backgroundColor: colors.white, borderRadius: radius.md, borderWidth: 1, borderColor: colors.slate200, padding: spacing.sm, gap: spacing.x4s },
  statValue: { fontSize: 32, fontWeight: "800", color: colors.deepForest },
  statLabel: { fontSize: 14, color: colors.slate500, fontWeight: "500" },
  companyMinList: { gap: spacing.x4s, marginBottom: spacing.xs },
  companyMinRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, paddingVertical: 10, paddingHorizontal: spacing.x2s },
  companyMinName: { fontSize: 15, fontWeight: "600", color: colors.slate900 },
  companyMinCount: { fontSize: 13, color: colors.slate500 },
  chartRow: { flexDirection: "row", gap: spacing.x3s, marginBottom: spacing.md, alignItems: "flex-end" },
  chartCol: { flex: 1, alignItems: "center", gap: spacing.x4s },
  chartBarValue: { ...typography.caption, color: colors.slate500 },
  chartBar: { width: "100%", maxWidth: 40, backgroundColor: colors.mossGreen, borderRadius: radius.sm, minHeight: 4 },
  chartLabel: { fontSize: 11, color: colors.slate500, textTransform: "capitalize" },
  activityList: { gap: spacing.x3s },
  activityRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.md, padding: 14 },
  activityLeft: { gap: 2 },
  activityName: { fontSize: 15, fontWeight: "600", color: colors.slate900 },
  activityType: { fontSize: 13, color: colors.slate500, textTransform: "capitalize" },
  activityPoints: { fontSize: 16, fontWeight: "700", color: colors.mossGreen },
  tableHeader: { flexDirection: "row", backgroundColor: colors.slate100, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, paddingVertical: 10, paddingHorizontal: spacing.x2s, marginBottom: spacing.x4s },
  tableHeaderCell: { fontSize: 12, fontWeight: "700", color: colors.slate500, textTransform: "uppercase" },
  tableRow: { flexDirection: "row", alignItems: "center", backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, paddingVertical: spacing.x2s, paddingHorizontal: spacing.x2s, marginBottom: spacing.x4s, gap: spacing.x4s },
  tableCell: { fontSize: 14, color: colors.slate900 },
  actionBtn: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: radius.sm, borderWidth: 1, alignItems: "center" },
  actionBtnWarn: { borderColor: colors.errorBorder, backgroundColor: colors.errorBg },
  actionBtnSuccess: { borderColor: colors.successBorder, backgroundColor: colors.successBg },
  actionBtnText: { fontSize: 12, fontWeight: "600" },
  inputSmall: { borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, padding: 6, fontSize: 12, color: colors.slate900, backgroundColor: colors.inputBg },
  createCard: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.md, padding: spacing.sm, gap: spacing.x2s, marginBottom: spacing.x3s },
  createTitle: { fontSize: 16, fontWeight: "700", color: colors.slate900 },
  createRow: { flexDirection: "row", gap: spacing.x3s, alignItems: "center" },
  input: { borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, padding: 10, fontSize: 14, color: colors.slate900, backgroundColor: colors.inputBg },
  createBtn: { backgroundColor: colors.mossGreen, borderRadius: radius.sm, paddingVertical: 10, paddingHorizontal: spacing.sm },
  createBtnText: { color: colors.white, fontSize: 14, fontWeight: "700" },
  companyCard: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.md, overflow: "hidden" },
  companyCardHeader: { flexDirection: "row", alignItems: "center", padding: spacing.xs },
  companyName: { fontSize: 16, fontWeight: "700", color: colors.slate900 },
  companyMeta: { fontSize: 13, color: colors.slate500, marginTop: 2 },
  expandIcon: { fontSize: 14, color: colors.slate500, marginLeft: spacing.x2s },
  companyDetails: { borderTopWidth: 1, borderTopColor: colors.slate200, padding: spacing.xs, gap: spacing.x2s },
  tokenActions: { flexDirection: "row", justifyContent: "flex-end" },
  genTokenBtn: { backgroundColor: colors.roleCompany, borderRadius: radius.sm, paddingVertical: spacing.x3s, paddingHorizontal: spacing.xs },
  genTokenBtnText: { color: colors.white, fontSize: 13, fontWeight: "600" },
  genBigBtn: { backgroundColor: colors.roleCompany, borderRadius: radius.md, paddingVertical: 14, paddingHorizontal: spacing.md, alignItems: "center", marginBottom: spacing.sm, alignSelf: "flex-start" },
  genBigBtnText: { color: colors.white, fontSize: 15, fontWeight: "700" },
  tokensTitle: { fontSize: 14, fontWeight: "700", color: colors.slate700 },
  tokenList: { gap: spacing.x4s },
  tokenHeader: { flexDirection: "row", backgroundColor: colors.slate100, borderRadius: radius.sm, paddingVertical: 6, paddingHorizontal: spacing.x3s },
  tokenHeaderCell: { fontSize: 11, fontWeight: "700", color: colors.slate500, textTransform: "uppercase" },
  tokenRow: { flexDirection: "row", alignItems: "center", paddingVertical: 6, paddingHorizontal: spacing.x3s, borderBottomWidth: 1, borderBottomColor: colors.slate100 },
  tokenCell: { fontSize: 13, color: colors.slate900 },
  tokenListFull: { gap: spacing.x4s },
  tokenTableHeader: { flexDirection: "row", backgroundColor: colors.slate100, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, paddingVertical: 10, paddingHorizontal: spacing.x2s, marginBottom: spacing.x4s },
  tokenTableRow: { flexDirection: "row", alignItems: "center", backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, paddingVertical: spacing.x2s, paddingHorizontal: spacing.x2s, marginBottom: spacing.x4s },
  roleTab: { paddingVertical: 10, borderRadius: radius.sm, alignItems: "center", backgroundColor: colors.slate100 },
  roleTabActive: { backgroundColor: colors.white, shadowColor: "#000", shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.08, shadowRadius: 3, elevation: 2 },
  roleTabText: { fontSize: 14, fontWeight: "600", color: colors.slate500 },
  roleTabTextActive: { color: colors.slate900 },
  filterRow: { flexDirection: "row", alignItems: "center", gap: spacing.x2s, marginBottom: spacing.xs },
  filterLabel: { fontSize: 14, fontWeight: "600", color: colors.slate700 },
  filterButtons: { flexDirection: "row", gap: spacing.x3s, flexWrap: "wrap" },
  filterBtn: { paddingHorizontal: 14, paddingVertical: spacing.x3s, borderRadius: 8, borderWidth: 1, borderColor: colors.slate200, backgroundColor: colors.white },
  filterBtnActive: { backgroundColor: colors.mossGreen, borderColor: colors.mossGreen },
  filterBtnText: { fontSize: 13, fontWeight: "600", color: colors.slate600 },
  filterBtnTextActive: { color: colors.white },
  primaryBtn: { backgroundColor: colors.mossGreen, borderRadius: 8, paddingVertical: spacing.x2s, alignItems: "center", marginBottom: spacing.xs },
  primaryBtnText: { color: colors.white, fontSize: 14, fontWeight: "700" },
  formCard: { backgroundColor: colors.white, borderRadius: 12, padding: spacing.xs, marginBottom: spacing.xs, borderWidth: 1, borderColor: colors.slate200 },
  formLabel: { fontSize: 13, fontWeight: "600", color: colors.slate700, marginBottom: spacing.x4s, marginTop: spacing.x3s },
  emptyText: { fontSize: 14, color: colors.slate500, textAlign: "center", padding: spacing.sm },
  dangerBtn: { backgroundColor: colors.errorBg, borderRadius: 6, paddingHorizontal: spacing.x2s, paddingVertical: 6 },
  dangerBtnText: { color: colors.error, fontSize: 12, fontWeight: "600" },
  listRow: { flexDirection: "row", alignItems: "center", padding: spacing.x2s, backgroundColor: colors.white, borderRadius: 8, marginBottom: spacing.x3s, borderWidth: 1, borderColor: colors.slate200 },
  listName: { fontSize: 14, fontWeight: "600", color: colors.slate900 },
  listEmail: { fontSize: 12, color: colors.slate500, marginTop: 2 },
  badge: { alignSelf: "flex-start", paddingHorizontal: spacing.x3s, paddingVertical: 3, borderRadius: 6 },
  badgeText: { fontSize: 12, fontWeight: "600" },
  analyticsSelector: { marginBottom: spacing.md },
  analyticsSelectorLabel: { fontSize: 15, fontWeight: "600", color: colors.slate700, marginBottom: spacing.x2s },
  analyticsUserList: { flexDirection: "row", flexWrap: "wrap", gap: spacing.x3s },
  analyticsUserBtn: { paddingHorizontal: spacing.xs, paddingVertical: 10, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.slate200, backgroundColor: colors.white },
  analyticsUserBtnActive: { backgroundColor: colors.mossGreen, borderColor: colors.mossGreen },
  analyticsUserBtnText: { fontSize: 14, fontWeight: "600", color: colors.slate700 },
  analyticsUserBtnTextActive: { color: colors.white },
  analyticsUserBtnEmail: { fontSize: 11, color: colors.slate500, marginTop: 2 },
  analyticsUserBtnEmailActive: { color: colors.creamLight },
  analyticsUserInfo: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.md, padding: spacing.sm, marginBottom: spacing.md, flexDirection: "row", alignItems: "center", gap: spacing.xs },
  analyticsUserName: { fontSize: 20, fontWeight: "700", color: colors.slate900 },
  analyticsUserStage: { fontSize: 14, color: colors.mossGreen, fontWeight: "600" },
  analyticsUserExp: { fontSize: 14, color: colors.slate500, marginLeft: "auto" },
  analyticsPlaceholder: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.md, padding: spacing.x2l, alignItems: "center" },
  analyticsPlaceholderText: { fontSize: 15, color: colors.slate500 },
  analyticsChartCard: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.md, padding: spacing.md, marginBottom: spacing.sm },
  analyticsChartHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: spacing.sm },
  analyticsChartTitle: { fontSize: 18, fontWeight: "700", color: colors.slate900 },
  analyticsChartStats: { flexDirection: "row", gap: spacing.md },
  analyticsChartStat: { alignItems: "flex-end" },
  analyticsChartStatValue: { fontSize: 20, fontWeight: "700", color: colors.mossGreen },
  analyticsChartStatLabel: { fontSize: 12, color: colors.slate500, fontWeight: "500" },
  analyticsChartRow: { flexDirection: "row", gap: 6, alignItems: "flex-end", minHeight: 180 },
  analyticsChartCol: { flex: 1, alignItems: "center", gap: spacing.x4s },
  analyticsChartBarValue: { fontSize: 10, color: colors.slate500, fontWeight: "600" },
  analyticsChartBar: { width: "100%", maxWidth: 48, backgroundColor: colors.mossGreen, borderRadius: radius.sm, minHeight: 4 },
  analyticsChartLabel: { fontSize: 10, color: colors.slate500, textTransform: "capitalize" },
  analyticsLayout: { flexDirection: "row", gap: spacing.md, minHeight: 600 },
  analyticsSidebar: { width: 220, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.md, padding: spacing.xs, alignSelf: "flex-start" },
  analyticsSidebarItem: { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 10, paddingHorizontal: spacing.x2s, borderRadius: radius.sm, marginBottom: spacing.x4s },
  analyticsSidebarItemActive: { backgroundColor: colors.slate100 },
  analyticsSidebarIcon: { width: 18, height: 18, alignItems: "center", justifyContent: "center" },
  analyticsSidebarLabel: { fontSize: 14, fontWeight: "500", color: colors.slate600 },
  analyticsSidebarLabelActive: { color: colors.mossGreen, fontWeight: "700" },
  analyticsMain: { flex: 1 },
  periodSelector: { flexDirection: "row", gap: spacing.x3s, marginBottom: spacing.xs },
  periodBtn: { paddingHorizontal: 14, paddingVertical: spacing.x3s, borderRadius: 8, borderWidth: 1, borderColor: colors.slate200, backgroundColor: colors.white },
  periodBtnActive: { backgroundColor: colors.mossGreen, borderColor: colors.mossGreen },
  periodBtnText: { fontSize: 13, fontWeight: "600", color: colors.slate600 },
  periodBtnTextActive: { color: colors.white },
  customDateRow: { flexDirection: "row", gap: spacing.x2s, marginBottom: spacing.xs },
  customDateField: { flex: 1 },
  customDateLabel: { fontSize: 13, fontWeight: "600", color: colors.slate700, marginBottom: spacing.x4s },
  customDateInput: { borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, padding: 10, fontSize: 14, color: colors.slate900, backgroundColor: colors.white },
});
