import { StyleSheet } from "react-native";
import { colors, radius } from "../../styles/tokens";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.white },
  fallbackRoot: { flex: 1, justifyContent: "center", alignItems: "center", padding: 24 },
  fallbackTitle: { fontSize: 22, fontWeight: "700", color: colors.slate900, marginBottom: 8 },
  fallbackText: { fontSize: 15, color: colors.slate500, textAlign: "center" },
  topbar: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: 20, paddingVertical: 12, backgroundColor: colors.white, borderBottomWidth: 1, borderBottomColor: colors.slate200 },
  topbarTitle: { fontSize: 18, fontWeight: "700", color: colors.slate900 },
  topbarRight: { flexDirection: "row", gap: 12, alignItems: "center" },
  backLink: { fontSize: 14, color: colors.mossGreen, fontWeight: "600" },
  navTabs: { flexDirection: "row", backgroundColor: colors.white, borderBottomWidth: 1, borderBottomColor: colors.slate200, paddingHorizontal: 16 },
  navTab: { paddingVertical: 12, paddingHorizontal: 16, borderBottomWidth: 2, borderBottomColor: "transparent" },
  navTabActive: { borderBottomColor: colors.mossGreen },
  navTabText: { fontSize: 14, fontWeight: "600", color: colors.slate500 },
  navTabTextActive: { color: colors.mossGreen },
  body: { padding: 24 },
  bodyInner: { maxWidth: 960, width: "100%", alignSelf: "center" },
  welcome: { fontSize: 16, fontWeight: "600", color: colors.slate500, marginBottom: 24 },
  pageTitle: { fontSize: 18, fontWeight: "700", color: colors.slate900, marginBottom: 16 },
  sectionTitle: { fontSize: 15, fontWeight: "700", color: colors.slate700, marginBottom: 8, marginTop: 16 },
  emptyText: { fontSize: 14, color: colors.slate500, textAlign: "center", marginTop: 24 },
  errorCard: { backgroundColor: colors.errorBg, borderWidth: 1, borderColor: colors.errorBorder, borderRadius: radius.sm, padding: 16, gap: 8 },
  errorText: { fontSize: 15, fontWeight: "600", color: colors.error },
  errorDetail: { fontSize: 13, color: colors.error },
  tableHeader: { flexDirection: "row", backgroundColor: colors.slate100, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, paddingVertical: 10, paddingHorizontal: 12, marginBottom: 4 },
  tableHeaderCell: { fontSize: 12, fontWeight: "700", color: colors.slate500, textTransform: "uppercase", letterSpacing: 0.5 },
  tableRow: { flexDirection: "row", alignItems: "center", backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, paddingVertical: 12, paddingHorizontal: 12, marginBottom: 4 },
  tableCell: { fontSize: 14, color: colors.slate900 },
  badge: { alignSelf: "flex-start", paddingHorizontal: 8, paddingVertical: 3, borderRadius: radius.sm },
  badgeText: { fontSize: 12, fontWeight: "600" },
  actionBtn: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.slate200, backgroundColor: colors.white, alignItems: "center" },
  actionBtnText: { fontSize: 12, fontWeight: "600", color: colors.slate700 },
  inputSmall: { fontSize: 13, color: colors.slate900, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, paddingHorizontal: 8, paddingVertical: 6, backgroundColor: colors.white },
  genBigBtn: { backgroundColor: colors.mossGreen, paddingHorizontal: 20, paddingVertical: 10, borderRadius: radius.sm },
  genBigBtnText: { color: colors.white, fontSize: 15, fontWeight: "700" },
  tokenCell: { fontSize: 13, color: colors.slate900 },
  tokenListFull: { gap: 4 },
  chartCard: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.md, padding: 24, marginBottom: 20 },
  chartRow: { flexDirection: "row", gap: 6, alignItems: "flex-end", minHeight: 180 },
  chartCol: { flex: 1, alignItems: "center", gap: 4 },
  chartBarValue: { fontSize: 10, color: colors.slate500, fontWeight: "600" },
  chartBar: { width: "100%", maxWidth: 48, backgroundColor: colors.mossGreen, borderRadius: radius.sm, minHeight: 4 },
  chartLabel: { fontSize: 10, color: colors.slate500 },
  analyticsUserInfo: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, padding: 16, marginBottom: 20, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  analyticsUserName: { fontSize: 18, fontWeight: "700", color: colors.slate900 },
  analyticsUserPoints: { fontSize: 16, fontWeight: "600", color: colors.mossGreen },
  analyticsPlaceholder: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, padding: 40, alignItems: "center", marginBottom: 20 },
  analyticsPlaceholderText: { fontSize: 15, color: colors.slate500 },
  filterBtn: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: colors.slate200, backgroundColor: colors.white },
  filterBtnActive: { backgroundColor: colors.mossGreen, borderColor: colors.mossGreen },
  filterBtnText: { fontSize: 13, fontWeight: "600", color: colors.slate600 },
  filterBtnTextActive: { color: colors.white },
  analyticsLayout: { flexDirection: "row", gap: 24, minHeight: 600 },
  analyticsSidebar: { width: 220, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.md, padding: 16, alignSelf: "flex-start" },
  analyticsSidebarItem: { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 10, paddingHorizontal: 12, borderRadius: radius.sm, marginBottom: 4 },
  analyticsSidebarItemActive: { backgroundColor: colors.slate100 },
  analyticsSidebarIcon: { width: 18, height: 18, alignItems: "center", justifyContent: "center" },
  analyticsSidebarLabel: { fontSize: 14, fontWeight: "500", color: colors.slate600 },
  analyticsSidebarLabelActive: { color: colors.mossGreen, fontWeight: "700" },
  analyticsMain: { flex: 1 },
  periodSelector: { flexDirection: "row", gap: 8, marginBottom: 16 },
  periodBtn: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: colors.slate200, backgroundColor: colors.white },
  periodBtnActive: { backgroundColor: colors.mossGreen, borderColor: colors.mossGreen },
  periodBtnText: { fontSize: 13, fontWeight: "600", color: colors.slate600 },
  periodBtnTextActive: { color: colors.white },
  customDateRow: { flexDirection: "row", gap: 12, marginBottom: 16 },
  customDateField: { flex: 1 },
  customDateLabel: { fontSize: 13, fontWeight: "600", color: colors.slate700, marginBottom: 4 },
  customDateInput: { borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, padding: 10, fontSize: 14, color: colors.slate900, backgroundColor: colors.white },
  tokenTableHeader: { flexDirection: "row", backgroundColor: colors.slate100, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, paddingVertical: 10, paddingHorizontal: 12, marginBottom: 4 },
  tokenTableRow: { flexDirection: "row", alignItems: "center", backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, paddingVertical: 12, paddingHorizontal: 12, marginBottom: 4 },
});
