import { StyleSheet } from "react-native";
import { colors, typography, radius, spacing } from "../../styles/tokens";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.white },
  fallbackRoot: { flex: 1, justifyContent: "center", alignItems: "center", padding: spacing.md },
  fallbackTitle: { fontSize: 22, fontWeight: "700", color: colors.slate900, marginBottom: spacing.x3s },
  fallbackText: { fontSize: 15, color: colors.slate500, textAlign: "center" },
  topbar: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: spacing.sm, paddingVertical: spacing.x2s, backgroundColor: colors.white, borderBottomWidth: 1, borderBottomColor: colors.slate200 },
  topbarTitle: { fontSize: 18, fontWeight: "700", color: colors.slate900 },
  topbarRight: { flexDirection: "row", gap: spacing.x2s, alignItems: "center" },
  backLink: { fontSize: 14, color: colors.mossGreen, fontWeight: "600" },
  navTabs: { flexDirection: "row", backgroundColor: colors.white, borderBottomWidth: 1, borderBottomColor: colors.slate200, paddingHorizontal: spacing.xs },
  navTab: { paddingVertical: spacing.x2s, paddingHorizontal: spacing.xs, borderBottomWidth: 2, borderBottomColor: "transparent" },
  navTabActive: { borderBottomColor: colors.mossGreen },
  navTabText: { fontSize: 14, fontWeight: "600", color: colors.slate500 },
  navTabTextActive: { color: colors.mossGreen },
  body: { padding: spacing.md },
  bodyInner: { maxWidth: 960, width: "100%", alignSelf: "center" },
  welcome: { ...typography.h3, color: colors.slate500, marginBottom: spacing.md },
  pageTitle: { fontSize: 18, fontWeight: "700", color: colors.slate900, marginBottom: spacing.xs },
  sectionTitle: { fontSize: 15, fontWeight: "700", color: colors.slate700, marginBottom: spacing.x3s, marginTop: spacing.xs },
  emptyText: { fontSize: 14, color: colors.slate500, textAlign: "center", marginTop: spacing.md },
  errorCard: { backgroundColor: colors.errorBg, borderWidth: 1, borderColor: colors.errorBorder, borderRadius: radius.sm, padding: spacing.xs, gap: spacing.x3s },
  errorText: { fontSize: 15, fontWeight: "600", color: colors.error },
  errorDetail: { fontSize: 13, color: colors.error },
  tableHeader: { flexDirection: "row", backgroundColor: colors.slate100, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, paddingVertical: 10, paddingHorizontal: spacing.x2s, marginBottom: spacing.x4s },
  tableHeaderCell: { fontSize: 12, fontWeight: "700", color: colors.slate500, textTransform: "uppercase", letterSpacing: 0.5 },
  tableRow: { flexDirection: "row", alignItems: "center", backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, paddingVertical: spacing.x2s, paddingHorizontal: spacing.x2s, marginBottom: spacing.x4s },
  tableCell: { fontSize: 14, color: colors.slate900 },
  badge: { alignSelf: "flex-start", paddingHorizontal: spacing.x3s, paddingVertical: 3, borderRadius: radius.sm },
  badgeText: { fontSize: 12, fontWeight: "600" },
  actionBtn: { paddingHorizontal: spacing.x3s, paddingVertical: 5, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.slate200, backgroundColor: colors.white, alignItems: "center" },
  actionBtnText: { fontSize: 12, fontWeight: "600", color: colors.slate700 },
  inputSmall: { fontSize: 13, color: colors.slate900, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, paddingHorizontal: spacing.x3s, paddingVertical: 6, backgroundColor: colors.white },
  genBigBtn: { backgroundColor: colors.mossGreen, paddingHorizontal: spacing.sm, paddingVertical: 10, borderRadius: radius.sm },
  genBigBtnText: { color: colors.white, fontSize: 15, fontWeight: "700" },
  tokenCell: { fontSize: 13, color: colors.slate900 },
  tokenListFull: { gap: spacing.x4s },
  chartCard: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.md, padding: spacing.md, marginBottom: spacing.sm },
  chartRow: { flexDirection: "row", gap: 6, alignItems: "flex-end", minHeight: 180 },
  chartCol: { flex: 1, alignItems: "center", gap: spacing.x4s },
  chartBarValue: { fontSize: 10, color: colors.slate500, fontWeight: "600" },
  chartBar: { width: "100%", maxWidth: 48, backgroundColor: colors.mossGreen, borderRadius: radius.sm, minHeight: 4 },
  chartLabel: { fontSize: 10, color: colors.slate500 },
  analyticsUserInfo: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, padding: spacing.xs, marginBottom: spacing.sm, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  analyticsUserName: { fontSize: 18, fontWeight: "700", color: colors.slate900 },
  analyticsUserPoints: { ...typography.h3, color: colors.mossGreen },
  analyticsPlaceholder: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, padding: spacing.xl, alignItems: "center", marginBottom: spacing.sm },
  analyticsPlaceholderText: { fontSize: 15, color: colors.slate500 },
  filterBtn: { paddingHorizontal: 14, paddingVertical: spacing.x3s, borderRadius: 8, borderWidth: 1, borderColor: colors.slate200, backgroundColor: colors.white },
  filterBtnActive: { backgroundColor: colors.mossGreen, borderColor: colors.mossGreen },
  filterBtnText: { fontSize: 13, fontWeight: "600", color: colors.slate600 },
  filterBtnTextActive: { color: colors.white },
  analyticsLayout: { flexDirection: "row", gap: spacing.md, minHeight: 600 },
  analyticsSidebar: { width: 220, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.md, padding: spacing.xs, alignSelf: "flex-start" },
  analyticsSidebarItem: { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 10, paddingHorizontal: spacing.x2s, borderRadius: radius.sm, marginBottom: spacing.x4s },
  analyticsSidebarItemActive: { backgroundColor: colors.slate100 },
  analyticsSidebarIcon: { width: 18, height: 18, alignItems: "center", justifyContent: "center" },
  analyticsSidebarLabel: { fontSize: 14, fontWeight: "500", color: colors.slate600 },
  analyticsSidebarLabelActive: { color: colors.mossGreen, fontWeight: "700" },
  analyticsMain: { flex: 1 },
  periodSelector: { flexDirection: "row", gap: spacing.x3s, marginBottom: spacing.xs },
  periodBtn: { paddingHorizontal: 14, paddingVertical: spacing.x3s, borderRadius: 8, borderWidth: 1, borderColor: colors.slate200, backgroundColor: colors.white },
  periodBtnActive: { backgroundColor: colors.mossGreen, borderColor: colors.mossGreen },
  periodBtnText: { fontSize: 13, fontWeight: "600", color: colors.slate600 },
  periodBtnTextActive: { color: colors.white },
  customDateRow: { flexDirection: "row", gap: spacing.x2s, marginBottom: spacing.xs },
  customDateField: { flex: 1 },
  customDateLabel: { fontSize: 13, fontWeight: "600", color: colors.slate700, marginBottom: spacing.x4s },
  customDateInput: { borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, padding: 10, fontSize: 14, color: colors.slate900, backgroundColor: colors.white },
  tokenTableHeader: { flexDirection: "row", backgroundColor: colors.slate100, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, paddingVertical: 10, paddingHorizontal: spacing.x2s, marginBottom: spacing.x4s },
  tokenTableRow: { flexDirection: "row", alignItems: "center", backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: radius.sm, paddingVertical: spacing.x2s, paddingHorizontal: spacing.x2s, marginBottom: spacing.x4s },
});
